{% set name = "e3fp" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/e3fp-{{ version }}.tar.gz
  sha256: c7fd01869f0d23cb1950ebb23b36173f1566614a83205b497a6875c04cf5d9e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python
    - mmh3 >=2.3.1
    - numpy >=1.11.3
    - scipy >=0.18.0
    - rdkit >=2016.03.4
    - sdaxen_python_utilities >=0.1.4

test:
  imports:
    - e3fp
    - e3fp.config

about:
  home: https://github.com/keiserlab/e3fp
  summary: Molecular 3D fingerprinting
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
    - sethaxen
