{% set name = "e3fp" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/e3fp-{{ version }}.tar.gz
  sha256: 8d5aa5e338665441a58d51d9f679da481e7f7ed48f4df1ed03fb759ccb4d9326

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - mmh3 >=2.3.1
    - numpy >=1.11.3
    - scipy >=0.18.0
    - rdkit >=2016.03.4
    - sdaxen_python_utilities >=0.1.5
    - smart_open >=1.8.3

test:
  imports:
    - e3fp
    - e3fp.config

about:
  home: https://github.com/keiserlab/e3fp
  summary: Molecular 3D fingerprinting
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
    - sethaxen
